export * from './MostPlayed'
export * from './LatestUpdates'
export * from './BestFPS'
export * from './NowStreaming'
export * from './MustPlayGame'
export * from './NintendoDirect'
export * from './HappeningNow'
export * from './Footer'